### ISSUE TITLE
High level comments 

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#102]
@aprajita @drphilmarshall Is there any big item missing from paper 2?

**Comment by drphilmarshall** [comment]
I don't think so, no - looks like a nice job to me!

I have a couple of high level comments:

1) Is AF complete or not? In the image separation distribution section it's claimed that it is not, but then we seem to say later that SW adds a significant number of group-scale lenses to the sample. This probably just needs clearer text/definitions, perhaps?

2) I still think we should be talking about ~20 promising new lens candidates, as opposed to 61 new candidates! We use the words "promising" and "total" when introducing the AF and RF samples, I think we should follow the same, very useful, convention when presenting the SW sample. I worry about people reading the abstract, getting excited about 61 new lenses, and then being disappointed when they see the images and our low grade assignments...

**Comment by drphilmarshall** [comment]
Oh - one other thing: I didn't see the "additional samples" question get resolved. What do we do with the Sygnet sample, and the RF serendipitous systems? Just include them as galaxy scale "RF" KCs and KLs?

**Comment by aprajita** [comment]
Looks v good @anupreeta27 , well done!
here's some top-level/quick comments (have lots of more detailed comments to be sent later)
1) I think we should compile other known lenses and mark them, the sygnet sample sticks out between RF & AF. Is it targeted or not
2) Happy to go with your preference of volunteers then citizen scientists sometimes
3) seems to be missing some link to SW1 in sects 2, 3, 4 I would suggest rordering the topics here a bit to be clear. it depends if we expect users to have read sw1, but also need to be careful that we don't make sw1 reducndant. so i woudl suggest having 2.1 data, 2.2 known lenses, 3 how cfhts represnted in sw interface, intro+ 3.1 old 2.2 + 3.2 simulations (old 3) + 3.3 duds & FPS (old 4)
also sims section should refer back to tests & results presented in SW1 
4)i think beginning of S5.1 should be cut down and simply refer to sw1, then start with brief intro then into "we decided…."
5) fig 4 "new" colour too similar to KC
6) agree with @drphilmarshall that we should split the sample into probable and possible based on grades so could reinstate the medium class we prviously had.  also could expand text about what the grades mean in §5.1, e.g. 1.3 means at least 1of us thinks probably a lens etc...
7) what about the compltetnes in our expert classification, how many kcs,kls did we not rank highly or reject?
8) sorry small comment but doesnt table 2 say that 100% of the KCs & KLs were recoved in stage 2?
9) for RF/AF sample please double check that when you use 'sample' in the text you mean KL+KC or just KL, it can get a bit confusing in parts
10) i  think a section could be added on the actual SW lenses using the SW new+known sample - other than the dashed histgrams in  Fig 8, there's not much discussion on the lenses SW citizens have found. more qualitative discussion of the candidates could be added, but this could be left to sw3?
11) After a quick read, my impression is that there's little emphasis on he new lenses themselves. what's the benefit of finding of these candadates if they are much like arc/ring finder, do our results just mean that while our sample contains "new" lenses there's not much gin in studying them as they are similar to previously known lenses. other than helping ind FPs and improving the robots have we not added any value
12) i thought future searches is in the domain of SW1, unless there are specific CFHT-LS lessons that need to be brought out
13) small comment on fig 8 also I think it should be easier to visually identify the SWnew+old when looking at the plot, the blue looks rather hidden in comparison to red and green, have you tried, solid symbols for SW new+known, and open circles for the rest? the sw gets a bit lost here
13b) also can u shade the sw known+new histograms in fig 8 so that it's clearer 
14) still not keen on SW name,but ok.  i have another draft email to you somewhere about the different CFHTLS type names currently used in the literature, we should homogenise our naming to one of those, will get back to you
15) if there is a cfht catalogue entry should we not give the cfhtls catalogue indetifier too in the table?
