### ISSUE TITLE
Paper 2: Footnote 1 - Master Lens Database

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#138]
http://admin.masterlens.org/index.php

Perhaps a comment is needed that an account is required to access it?

I can just foresee a few grumbles from *some* volunteers, that a source quoted in Zooniverse paper is not easily accessible for the average user.

**Comment by ccld** [comment]
Years ago I have asked an account to browse the database but got no reply/authorization/credentials.

http://admin.masterlens.org/search.php?   That's Basic Search requiring "Authorization" which is not granted!

**Comment by anupreeta27** [comment]
The reason why MLD is not public yet is because the team is checking and vetting all the information in the database. 
But my reference to this link - http://admin.masterlens.org/index.php is to show the summary (text in red) of all lenses in MLD which is publicly visible on this page if you scroll down.

**Comment by ccld** [comment]
Sorry Anu: the links in red summary don't give public access. (example: that was my previous basic link)

**Comment by anupreeta27** [comment]
@ccld  I mean this 

![screen shot 2015-04-18 at 9 49 19 pm](https://cloud.githubusercontent.com/assets/1819690/7215473/f14ba208-e614-11e4-8cb3-b19eb494bfd9.png)

this is publicly visible.

**Comment by ccld** [comment]
No: basic search and so on requires an account and password which I could not get from the MLD owner.

**Comment by Capella05** [comment]
Oh - I think I understand all the confusion! 

We (myself and Claude) are expecting to be able to be able to search the database, as it is quoted in the paper,but (correct me if I am wrong Anu) the reference in the paper is only substantiating the number of lenses currently discovered?

I think this will cause  a lot of negative feedback from within the Zooniverse  community - without any clarification they will also expect to be able to navigate around the site without hindrance. Being prompted for authentication will give the impression that they are specifically being excluded from the data.

**Comment by surhudm** [comment]
Hi guys,

I agree it is a bit frustrating that the entire master lens database
is not visible and the basic search functions are not available.

But the paper is just referring to it for the fact that there has at
the moment we have had "discovery of over 500 lenses till date".

In the paper, Anupreeta is just citing the public information listed
on that page:

"""
Containing 656 Gravitational Lens Systems:

423 Grade-A Lenses
103 Grade-B Lenses
92 Grade-C Lenses
"""

Citing such information is standard practice. This also helps to
highlight and attract attention of the professional lensing community,
so that they help curate some of the lenses in the database.

We hope we would be able to convince the PI to recruit enthusiastic
volunteers from the citizen science community such as you for these
tasks.

Apologies that it has taken such a long time!

Cheers,
Surhud

**Comment by anupreeta27** [comment]
@Capella05  you got it right. I am only referring to the main page on which there is a summary given in red as i show in the snapshot and as pointed by Surhud too. I am not asking anyone to click on any further links or do any kind of search. Also, just to be clear - I am referring to the Grade A and B lenses which are most promising and these are about 500.

**Comment by surhudm** [comment]
@Capella05, I think our replies crossed!

Yes, the citation is merely meant for the number of lenses.

Unfortunately we do not have the privileges to currently make the Master lens database public or to given the citizen science community access. But I do not think this should be a requirement to quote any reference.

There are a number of new articles from different journals which are also not publicly accessible to the citizen scientists (yes you can check most of them on the arxivs, but this is not binding on any of the authors of such papers). However, this does not mean these papers should not be cited.

I hope that clarifies the issue. As I said before, I can understand your frustration with this.

**Comment by Capella05** [comment]
Thank you both for replying and clearing that up!
