### ISSUE TITLE
MNRAS Style Guide doesn't allow numbered papers

### ISSUE THREAD

**Issue by chrislintott** [drphilmarshall/SpaceWarps#140]
Suggest renaming second paper to just Spacewarps : New lens...

(We found with GZ it really helped to have the project name first)

**Comment by surhudm** [comment]
Is this something new? I have seen paper in MNRAS with numbers as recently as the beginning of this year.

For example:
http://dx.doi.org/10.1093/mnras/stu1075
http://dx.doi.org/10.1093/mnras/stv600

**Comment by anupreeta27** [comment]
@drphilmarshall @aprajita 
i was under the impression that we are using SW I and SW II in our papers. i didn't realize that paper I has just SW. what do we want to do about this since from the above given references, it seems it should be allowed in mnras journals?

**Comment by aprajita** [comment]
yes i think I and II etc are allowed, of the form Space Warps - I. Crowd ….  and Space Warps - II. New

but i don't mind whether we drop the numerals or not., having them means specific papers are more easily referenced, so suggest adding I to paper I.

**Comment by anupreeta27** [comment]
I agree with @aprajita. it would be good to keep the numbers for some core initial SW papers and then have "Space Warps:" for other papers from SW. This reminds me that the 9io9 paper ( which is not yet accepted) should have this prefix in the title, can't do anything about the already accepted paper of Kueng et al. now.

**Comment by aprajita** [comment]
i'm not sure we need some papers with and some without - wouldn't it be better to have all the same?

perhaps the argument is these two go together and are being submitted together

**Comment by anupreeta27** [comment]
i think the argument for giving these two papers the numbers is to imply that these are the main two SW papers in the context of various other SW papers being published earlier (e.g. Kueng et al. & Geach et al.) or later. And, the reason for not choosing numbers for the rest is because we wouldn't know before hand how to assign numbers e.g. what should we choose/have chosen for Geach et al. ? Also, Geach et al. paper is just one system from sw-vics82, not the main sw-vics82 paper. I think this can get complicated pretty soon.

**Comment by ccld** [comment]
see score XXXVII as of april 13, of "intermediate results"  :-)

Planck intermediate results. XXXVII. Evidence ...

**Comment by drphilmarshall** [comment]
I guess internally we may have some confusion because we refer to these two
papers as Paper I and Paper II, but I don't think this means that they need
to have numerals in the titles. Paper I's title has been numeral-free since
we started writing it, following the Galaxy Zoo and Planet Hunters examples.

Also, because we are a service, and so have done projects with different
datasets and different survey teams, I think numbering the papers in the
titles somehow makes even less sense than it would in Galaxy Zoo or Planet
Hunters, which have largely unchanging science teams. It seems odd to me
that we would prefix the VICS82 survey paper with "Space Warps - III. ",
doesn't it? But "Space Warps: New Lens Candidates in the VICS82 Survey"
seems OK, to me.

Having two papers at the start, labelled I and II, might look a bit odd
when the VICS82 survey paper doesn't have a number, but I don't have strong
feelings about this: I agree that it does make some sense to treat these
first two papers as a series of two. Happy to go with either.


I'm not sure the Geach et al Letter title should necessarily be renamed to
start with "Space Warps", because it's not a Space Warps methodology paper.
This is part of the "we're a service" mentality: it would be nice if we
could get to the point where survey teams wrote papers with titles of their
choosing about lens searches they have done, having successfully
out-sourced the visual inspection step to us just because that's what made
sense. I wouldn't want new survey teams being put off from working with us
just because they knew we were going to ask for their paper titles to start
with "Space Warps"! In contrast, Galaxy Zoo and Planet Hunters are not
services: they're competing teams, looking for planets or classifying
galaxies in public datasets and whose science teams do the follow-up work
themselves.

I also notice that our policy doesn't say anything about the naming of
papers at all - so I guess its up to the authors of each one! I guess we
could ask Jim and see what he says.
