### ISSUE TITLE
Figure 5: Distracting yellow histogram

### ISSUE THREAD

**Issue by chrislintott** [drphilmarshall/SpaceWarps#147]
I find the histogram in figure 5 more distracting than useful - the gap between 1 and 2 (presumably the result of fractional binning) is misleading, but more to the point I don't think it adds to the main message of the figure. I would drop it and leave the trajectories.

I discussed this with Phil so am assigning to him.

**Comment by drphilmarshall** [comment]
Anu went one step further and queried the whole figure: certainly it is old, s.t. the y-axis no longer matches our definition of skill / information gain. I have commented out the whole thing until further notice - I don't think the paper is much poorer for it. BTW the yellow histogram was also patchy because its only 200 agents (unlike in the trajectories plot, where the histogram shows all subjects...)
