### ISSUE TITLE
Paper II - Table 3 - redshift

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#160]
May be it would be better to put z spectroscopic whenever available by SDSS CrossID for DR12:
(in particular SW50 zp 0, SW2 zp 0.7, SW27 zp 0.7)
SELECT s.specobjid, s.ra, s.dec, s.z
FROM #upload u
      JOIN #x x ON x.up_id = u.up_id
      JOIN SpecObjAll s ON s.specObjID = x.specObjID

name specobjid ra dec z 
SW29 751117935786878976 32.741433 -8.747394 0.4472963 
SW44 4949486599722954752 33.105116 -8.8698145 0.7594223 
SW30 4949470107048538112 33.810958 -9.411186 0.7202559 
SW20 4940601441343172608 36.388835 -5.5346305 0.5661425 
SW22 4938319405026832384 37.535984 -5.6774292 0.4980913 
SW13 4941673740108492800 37.846387 -8.4259299 0.5408069 
SW50 1489708835068209152 209.35367 56.270643 0.3601365 
SW51 1489581566597294080 210.11631 54.174603 1.0405.. doubtful (DR7 z_spec 0.6, zconf 0.3)
SW15 1305038708210165760 210.12594 57.743725 0.3819141 
SW2 7660847099814801408 211.34249 57.725904 0.5162626 
SW52 7591033883350200320 213.82905 51.65422 0.2891185 
SW4 7659497998292545536 217.39258 56.428153 0.5136735 
SW27 7656269282347249664 217.73322 57.408888 0.6052749 
SW37 7554838785214312448 218.47354 54.386376 0.6536468 
SW5 7563881718294966272 218.72698 52.480872 0.625356 
SW6 7656204960917024768 219.11651 56.642745 0.5266066 
SW57 7564005138475184128 219.21496 53.118439 0.5760912 
SW17 7564012285300764672 219.24248 53.635536 0.6104435 
SW58 7554790406702690304 219.96084 54.768737 0.7310352 
SW38 4859508884861808640 330.56352 1.3566691 0.3139308 
SW7 4859549841669943296 330.73677 2.5760996 0.4822684

**Comment by anupreeta27** [comment]
@ccld  thanks a lot. will leave out the z=1.0 system since its photo_z is 0.6 and as you say its doubtful.

**Comment by aprajita** [comment]
@ccld what's the match radius used to the SDSS spec IDs?
when I run the crossID with ANu;s latest table of new candidates, I only get 3 matches within 3", the rest are >70")
So I think the only matches to the DR12 spec database are SW4, SW15 & SW30 (z=0.513981, 0.381946, 0.447508).

**Comment by ccld** [comment]
@Aprajita, @Anu
I picked up the table 3 and used CrossId for DR12: search type "Images"/"Nearest Primary Object"/"Join with Spectra"
/Search radius [arcmin] 0.1  (6"). 

Before that you could visualize the 58 SW list in "Image List Tool" and put "Drawing options" :Objects with spectra", scale 0.05. You'll see the only offset spectrum is SW13 centered on arc instead of lens deflector.

I count 21 matches ( of which 1 bad fitting lines).
Hope this helps

**Comment by aprajita** [comment]
hi @ccld - thanks very much. 

I used the Spectra/Nearest Primary Object and got 3 matches also using table 3 (but with 48 new SW objects)

I've now tried the images join with spectra search as you did, and get 15 matches with SW4 with 2 spec IDs (sdss & boss). I've added the matched list with separations in arcsec for the photo & spec objects.

SW13 is the redshift of the northern galaxy that may be contributing to the lensing so is still relevant but will need a note in table3 if included.

i'm not sure why the direct spectra rather than image search didn't work … @ccld have you seen something like this before?

thanks!



#SELECT ,,,,,,,,,,,,,,,,,
#   p.objID, p.ra, p.dec,,,,,,,,,,,,,,,
#   dbo.fPhotoTypeN(p.type) as type,,,,,,,,,,,,,,,,,
#   p.modelMag_u, p.modelMag_g, p.modelMag_r, p.modelMag_i, p.modelMag_z,,,,,,,,,,,,,
#   s.specObjID, s.ra, s.dec, s.z,,,,,,,,,,,,,,
#FROM #upload u,,,,,,,,,,,,,,,,,
#      JOIN #x x ON x.up_id = u.up_id,,,,,,,,,,,,,,,,,
#      JOIN PhotoTag p ON p.objID = x.objID,,,,,,,,,,,,,,,,,
#      JOIN SpecObjAll s ON p.objID = s.bestObjID,,,,,,,,,,,,,,,,,
#ORDER by x.up_id,,,,,,,,,,,,,,,,,
#,,,,,,,,,,,,,,,,,
#Table1,,,,,,,,,,,,,,,,,
name,ra1,Dec-01,objID,ra,dec,type,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z,specObjID,ra2,Dec-02,z,Psep,Ssep
SW2,211.3426,57.7259,1.23766E+18,211.3425298,57.72583262,GALAXY,21.58276,20.62061,20.11274,19.32245,18.9161,7.66085E+18,211.34249,57.725904,0.5162626,0.27758,0.21197
SW4,217.3926,56.4281,1.23766E+18,217.392542,56.42808066,GALAXY,21.67703,20.71065,19.11223,18.22124,17.98101,1.3073E+18,217.39257,56.428086,0.5142316,0.13489,0.07812
SW4,217.3926,56.4281,1.23766E+18,217.392542,56.42808066,GALAXY,21.67703,20.71065,19.11223,18.22124,17.98101,7.6595E+18,217.39258,56.428153,0.5136735,0.13489,0.19492
SW5,218.727,52.4808,1.23766E+18,218.7269957,52.48080728,GALAXY,22.91544,22.4654,20.24244,19.06766,18.57615,7.56388E+18,218.72698,52.480872,0.625356,0.028,0.26289
SW6,219.1164,56.6425,1.23766E+18,219.1166717,56.64260822,GALAXY,23.13996,21.40491,19.96651,19.15594,18.96555,7.6562E+18,219.11651,56.642745,0.5266066,0.66418,0.90848
SW13,37.8468,-8.4266,1.23765E+18,37.84638725,-8.425927506,GALAXY,26.57743,21.47123,19.95268,19.00673,18.53094,4.94167E+18,37.846387,-8.4259299,0.5408069,2.83225,2.82535
SW15,210.126,57.7437,1.23766E+18,210.1258996,57.74372835,GALAXY,21.60859,20.52129,18.7528,18.12656,17.77518,1.30504E+18,210.12594,57.743725,0.3819141,0.21822,0.14625
SW17,219.2425,53.6355,1.23766E+18,219.2424854,53.63545403,GALAXY,22.07799,21.43781,20.36746,19.63469,19.19023,7.56401E+18,219.24248,53.635536,0.6104435,0.1684,0.13649
SW20,36.3888,-5.5346,1.23768E+18,36.38883831,-5.534634263,GALAXY,26.54447,21.63447,19.93187,18.9346,18.40067,4.9406E+18,36.388835,-5.5346305,0.5661425,0.18454,0.16668
SW22,37.5359,-5.6774,1.23768E+18,37.5359861,-5.677428002,GALAXY,22.5501,21.91325,20.46036,19.51899,19.17447,4.93832E+18,37.535984,-5.6774292,0.4980913,0.32451,0.31875
SW28,217.7333,57.4088,1.23766E+18,217.7331931,57.4088273,GALAXY,22.0082,20.65581,19.89174,19.06592,18.68188,7.65627E+18,217.73322,57.408888,0.6052749,0.22939,0.35274
SW30,32.7414,-8.7474,1.23765E+18,32.74143431,-8.747403235,GALAXY,23.83868,21.07242,19.31543,18.50801,17.97738,7.51118E+17,32.741433,-8.747394,0.4472963,0.12264,0.1194
SW31,33.8109,-9.4111,1.23767E+18,33.81095735,-9.411183155,GALAXY,26.10302,21.88648,20.6189,19.36837,18.76365,4.94947E+18,33.810958,-9.411186,0.7202559,0.3621,0.37188
SW38,218.4736,54.3862,1.23766E+18,218.4734928,54.38631243,GALAXY,25.16365,21.59713,20.8344,19.8723,19.47535,7.55484E+18,218.47354,54.386376,0.6536468,0.46294,0.64596
SW39,330.5635,1.3567,1.23768E+18,330.5635088,1.356671924,GALAXY,22.80645,19.62202,17.92382,17.31108,17.03821,4.85951E+18,330.56352,1.3566691,0.3139308,0.10598,0.13252
SW46,33.1051,-8.8697,1.23767E+18,33.10512442,-8.86981154,GALAXY,23.81379,21.34618,20.44766,19.21494,18.63269,4.94949E+18,33.105116,-8.8698145,0.7594223,0.41083,0.4161

**Comment by aprajita** [comment]
Hi again @ccld 
I realised I've been using an old input table. Will try again now. ignore previous post.
thanks

**Comment by aprajita** [comment]
Hi @ccld 

I also get 22 matches now in 0.1', sorry about the confusion earlier. 

Anyway, in the list of 22:
- SW4 has 2 spectroscopic IDs as I mentioned earLIER
- SW13 is the z of the possible nearby deflector.
- SW52 doubtful as you mentioned

there'a  couple of other nearby spectra (group members?)  that might be relevant in future papers that I've made a note of.

I still don't understand why a direct spectra search doesn't give the same results...

thanks for your help & sorry for causing confusion. 
@anupreeta27  please reclose when you've decided whether to include SW13

Aprajita.

**Comment by aprajita** [comment]
OK,  can now get all 22 spectra through the "spectra" search if I choose 'All nearby spectra'

**Comment by anupreeta27** [comment]
i suppose we can close this!

**Comment by anupreeta27** [comment]
@aprajita thanks for checking. 
sorry, i wanted to mention that i also checked using a similar radius as @ccld and found similar results.
