### ISSUE TITLE
Emulate dynamic stage 2 by re-running stage 2 with just the high stage 1 skill users

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#73]
If we had only asked the high skill users to take part in stage 2, we might have made a cut in stage 1 skill at say 0.2, and then only showed them the refinement app. We can emulate this by ignoring all agents with names not on this list. What happens to the completeness/purity? Do we have fewer false negatives? And do we see any lensed quasars appearing? This is worth a try I think: it's one way to address the false negatives problem (issue #68), which I think becomes more pressing since we discovered that the stage 2 agents don't know anything about lensed quasars... What do you think? We'd have to read the CFHTLS stage 1 agent names first, then propagate (watch out for the VICS82 stage 1 agents, thats a different bureau!)

**Comment by anupreeta27** [comment]
@cpadavis @drphilmarshall  
sorry, i don't remember if there are any updates on this issue.

**Comment by cpadavis** [comment]
I looked into this a while back and must have mentioned it somewhere else.

I reran everything on the (slightly newer than final) catalogs and found this. (I used the slightly newer than final catalogs because the pickles had a couple extra attributes that made it easier to run this procedure. The impact is minimal.):

There are this many IDs in both bureaus:  782
There are this many IDs in both bureaus with non-zero positive skill:  670
There are this many IDs in both bureaus with stage1 skill > 0.1:  498

From this we have a collection of 3988 subjects (lose only 44 subjects).

Here is the distribution of skill for the users in both stages. The red dashed line is the (arbitrary) cutoff of skill = 0.1:
![stage_skill](https://cloud.githubusercontent.com/assets/1781988/6405341/06efc5dc-bdd7-11e4-80fc-f2f0fcd2ce9d.png)
You'll notice that a hard cut on stage1 skill isn't super discriminating re: stage2 skill. Because I think you might be interested in knowing these as well, here are the plots for PL and PD. Note that I took out users whose PL and PD = 0.5 exactly; those are the 112 users who registered and then... didn't do much?

![pl](https://cloud.githubusercontent.com/assets/1781988/6405452/71ab83ba-bdd8-11e4-8dbc-ab1edc708866.png)
![pd](https://cloud.githubusercontent.com/assets/1781988/6405453/72ee0e28-bdd8-11e4-9977-8ef07d47f5f3.png)


It turns out that the roc curve does not change much. You perform slightly worse than using everyone, but you are also only using a quarter of the population:

![roc](https://cloud.githubusercontent.com/assets/1781988/6404610/b6608ed8-bdce-11e4-8f4c-1b302d878ec9.png)

**Comment by anupreeta27** [comment]
@cpadavis isn't it counter-intuitive that skilled users are doing slightly worse than all users? do you know what's happening?

**Comment by cpadavis** [comment]
so I think the primary issue is that selecting on stage 1 skill is not a good predictor for stage 2 skill (and that seems mostly to be from the PDs and not the PLs). Another factor to keep in mind is that it isn't stage 2 skilled users do worse than stage 2 unskilled users. (Actually, I show in issue #90 that high skill users DO do better than stage 2 unskilled users.) Instead, what this shows is that users selected on stage 1 skill do worse than the _entirety_ of stage 2 users. This is to say that even 'unskilled' users contribute information (plus there were other skilled stage 2 users we didn't include because they weren't in stage 1, and again the caveat that selecting on stage 1 skill isn't that good a predictor).

**Comment by anupreeta27** [comment]
@drphilmarshall @cpadavis 
i still don't fully understand e.g. fig 13 of paper I implies that stage 1 high skill users do have high skill at stage 2. is that fig. outdated then?

**Comment by cpadavis** [comment]
I would say that the interpretation in the figure caption ('may reduce noise in the system') is outdated and we should be able to definitively say yes or no. (Though now I'm not sure how to precisely probe 'reduce noise'.)

I was worried maybe I was cutting at too low a skill threshold, so I remade the roc curve cut at skill = 0.25 instead (that is where the vertical dashed line is in figure 13):

![roc](https://cloud.githubusercontent.com/assets/1781988/6416853/1a89860a-be5e-11e4-8e41-af943e36dbe8.png)

This time we have 326 users and we lost something like 70 subjects. They still do marginally worse, but only marginally so.

Figure 13 shows (just like the ROC curve does here) that you get nearly the same roc curve using just the stage 1 veterans (since high stage 1 skill AND high stage 2 skill together imply that you also made a large number of classifications). Users who had high stage 1 skill but low stage 2 skill generally made few classifications in stage 2 and so didn't contribute much to stage 2. The statement that you could reduce the noise in the system comes from the combination of these facts.

I think my statement that high stage 1 skill does not necessarily imply high stage 2 skill is borne out in figure 13. Even though our eye is drawn to the bigger circles, there are _many_ small circles below the stage 2 skill = 0.1 dashed line. However our central intention with the figure (that cutting on high stage 1 skill does not throw out that much information) is emphasized by the circle size, and the roc curve supports it as well.

(I think we should be _impressed_ and not _distraught_ that the top quarter of the spacewarps population (for some definition of 'top quarter') is able to do 99% of the work on their own.)
